# -*- coding: utf-8 -*-
"""bab9690W14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ucPY2H3aK0-uWcExZISIFt9oLgdpjDIV
"""

# Write a function that takes two lists representing sets (with no duplicates) which returns a list of the intersection.
# (use only loops and sequence indexing with no method calls except append).
# Use a nested loop in your implementation. Test on the list A = [2, 4, 5, 6] and B = [4, 6, 7, 8].

def findIntersection(listA, listB):
  #temporary list of intersection values
  intersection = []
  #loop thru first list
  for a in listA:
    #loop thru second list
    for b in listB:
      #save matches
      if a == b:
        intersection.append(a)
  return intersection #return finished list


#TEST

A = [2, 4, 5, 6]
B = [4, 6, 7, 8]

findIntersection(A,B) #returns [4,6]