# -*- coding: utf-8 -*-
"""git_session.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d70ufse8PhDJOh1vH9WF2nDmpghc6koy
"""

def intersection_list(A, B):
    result = []

    for element_A in A:
        for element_B in B:
            if element_A == element_B:
                result.append(element_A)
                break  # Once a match is found, break inner loop

    return result

# Test with given lists A and B
A = [2, 4, 5, 6]
B = [4, 6, 7, 8]

result_intersection = intersection_list(A, B)
print("Intersection of A and B:", result_intersection)