# -*- coding: utf-8 -*-
"""jg6004.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16pwLuTtgjuAL69wkw5f3y7QdfyutBhb-
"""

def intersection(a, b):
  intersect = []
  for i in a:
    if i in b:
      intersect.append(i)
  return intersect